### ISSUE TITLE
Unable to scroll landingpage / shelves

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#438]
For some viewers, when you use the right or left controls of theTileSlider component, it doesn't scroll.

It's not happening on all devices. But we have a couple of machines showing the behavior.

So far, it looks like it is NOT related to:
- OS: happens on windows, mac, ios
- Browser: happens on chrome, safari, firefox
- Screensize: same device, different screens, same issue
- Timing related: it happens consistently on a particular device

It seems to be introduced as in [v4.26.0 ](https://github.com/jwplayer/ott-web-app/pull/367), when the web app got upgraded to React 18.

https://github.com/jwplayer/ott-web-app/assets/42120041/e99e1010-dc89-4e61-9b85-8b5e506d0b17

https://github.com/jwplayer/ott-web-app/assets/42120041/f5aec2d4-6af5-426e-8b91-086fdb9bd300

https://github.com/jwplayer/ott-web-app/assets/42120041/0355e070-da19-408d-a2f9-d7f3ac75498f

https://github.com/jwplayer/ott-web-app/assets/42120041/76e781cd-9644-43b1-8c48-ac11948571a1

**Comment by marcovandeveen** [comment]
Update:
The behavior can be traced back to whether the slider is animated. 
- This is based on some 'browser magic' here: https://github.com/jwplayer/ott-web-app/blob/develop/src/components/TileDock/TileDock.tsx#L69
- Some browsers give this as a setting, but others don't, and [derive it from OS settings](https://stackoverflow.com/questions/59708960/how-do-i-change-the-prefers-reduced-motion-setting-in-browsers)

The preview link in  https://github.com/jwplayer/ott-web-app/pull/437/files fixes it.

**Comment by ChristiaanScheermeijer** [comment]
This issue is fixed by #437, right?

**Comment by budzworthy** [comment]
@ChristiaanScheermeijer yes and no... that fix fixes the majority of issues, but we still have a repro on ipad that's still broken with the new code.

**Comment by ChristiaanScheermeijer** [comment]
This is fixed in the new TileSlider #580
